// tslint:disable
/**
 * tradin.api.server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface PackageJson
 */
export interface PackageJson {
    /**
     * 
     * @type {string}
     * @memberof PackageJson
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof PackageJson
     */
    version?: string;
    /**
     * 
     * @type {string}
     * @memberof PackageJson
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof PackageJson
     */
    author?: string;
}


